export { getCleanNumber } from "./getCleanNumber"
export { getFirstLetter } from "./getFirstLetter"
export { capitalizeFirstLetter } from "./capitalizeFirstLetter"
export { getLastCharacters } from "./getLastCharacters"
export { formatTime } from "./formatTime"
export { getMinutesText } from "./getMinutesText"
export { cleanSpaces } from "./cleanSpaces"
export { trimText } from "./trimText"
